---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kubernetes-bootcamp
  name: kubernetes-bootcamp
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: kubernetes-bootcamp
---
