apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookapp-deployment
  labels:
    app: bookapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookapp
  template:
    metadata:
      labels:
        app: bookapp
    spec:
      containers:
      - name: bookapp
        image: docker.io/probaln/bookapp:1.0.1
        imagePullPolicy: Always
---
