apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookapp-deployment
  labels:
    app: bookapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookapp
  template:
    metadata:
      labels:
        app: bookapp
    spec:
      containers:
      - name: bookapp
        image: docker.io/probaln/bookapp:1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 45
          timeoutSeconds: 45
          httpGet:
            path: /actuator/health/liveness
            port: 8080
        readinessProbe:
          initialDelaySeconds: 45
          timeoutSeconds: 45
          httpGet:
            path: /actuator/health/readiness
            port: 8080
---
