apiVersion: v1
kind: Service
metadata:
  name: bookapp-service
  labels:
    app: bookapp
spec:
  type: LoadBalancer
  selector:
    app: bookapp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
