apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-book-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
spec:
  entrypoint: test-book
  templates:
  - name: test-book
    container: 
      image: docker.io/probaln/test-bookapp:v3
      command: ["sh"]
      args: ["integ-test/test-initialization.sh","http://a4a91f423eaf04b62b1354796a089f04-953826043.us-east-2.elb.amazonaws.com:8080"]
