apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
spec:
  entrypoint: test-three-steps

  templates:
  - name: test-three-steps
    # Instead of just running a container, this template runs a seq of containers
    steps:
    - - name: Initialization
        template: test-book
        arguments:
          parameters:
          - name:  test_script_name
            value: integ-test/test-initialization.sh 
          - name: cluster_url
            value: http://a4a91f423eaf04b62b1354796a089f04-953826043.us-east-2.elb.amazonaws.com:8080
    - - name: AddBook
        template: test-book
        arguments:
          parameters:
          - name:  test_script_name
            value: integ-test/test-add.sh 
          - name: cluster_url
            value: http://a4a91f423eaf04b62b1354796a089f04-953826043.us-east-2.elb.amazonaws.com:8080
    - - name: PatchBook
        template: test-book
        arguments:
          parameters:
          - name:  test_script_name
            value: integ-test/test-patch.sh 
          - name: cluster_url
            value: http://a4a91f423eaf04b62b1354796a089f04-953826043.us-east-2.elb.amazonaws.com:8080
    - - name: UpdateBook
        template: test-book
        arguments:
          parameters:
          - name:  test_script_name
            value: integ-test/test-update.sh 
          - name: cluster_url
            value: http://a4a91f423eaf04b62b1354796a089f04-953826043.us-east-2.elb.amazonaws.com:8080
    - - name: DeleteBook
        template: test-book
        arguments:
          parameters:
          - name:  test_script_name
            value: integ-test/test-delete.sh 
          - name: cluster_url
            value: http://a4a91f423eaf04b62b1354796a089f04-953826043.us-east-2.elb.amazonaws.com:8080

  - name: test-book
    inputs:
      parameters:
      - name: test_script_name
      - name: cluster_url
    container: 
      image: docker.io/probaln/test-bookapp:v3
      command: ["sh"]
      args: ["{{inputs.parameters.test_script_name}}", "{{inputs.parameters.cluster_url}}"]

